/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as IndexRouteImport } from './routes/index';
import { Route as TokensTokenRouteImport } from './routes/tokens.$token';

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const TokensTokenRoute = TokensTokenRouteImport.update({
  id: '/tokens/$token',
  path: '/tokens/$token',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/tokens/$token': typeof TokensTokenRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/tokens/$token': typeof TokensTokenRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/tokens/$token': typeof TokensTokenRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/tokens/$token';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/tokens/$token';
  id: '__root__' | '/' | '/tokens/$token';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  TokensTokenRoute: typeof TokensTokenRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/tokens/$token': {
      id: '/tokens/$token';
      path: '/tokens/$token';
      fullPath: '/tokens/$token';
      preLoaderRoute: typeof TokensTokenRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TokensTokenRoute: TokensTokenRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
